TrajectoryPlannerROS:
  holonomic_robot: false
  max_vel_x: 0.4
  min_vel_x: 0.1

  max_vel_theta: 0.5
  min_vel_theta: -0.5

  min_in_place_vel_theta: 0.2

  escape_vel: -0.2

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true

  meter_scoring: true
