controller_frequency: 5.0
TrajectoryPlannerROS:
  holonomic_robot: false
  meter_scoring: true
  max_vel_x: 1.0
  min_vel_x: -1.0
  max_vel_y: 1.0
  min_vel_y: -1.0
  max_vel_theta: 1.0
  max_in_place_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: -1.0

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 3.14159
