# Footprint of the robot with (0,0) being the center (in meters)
# footprint: [[-1.25, -0.66], [-1.25, 0.66], [1.25, 0.66], [1.25, -0.66]]
robot_radius: 0.1

# Frequency in Hz for the costmap to publish display information
publish_frequency: 5.0

# Delay in transform tf data that is tolerable in seconds
transform_tolerance: 0.2
