local_costmap:
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
      sensor_frame: laser_link
      data_type: LaserScan
      topic: scan
      marking: true
      clearing: true
      max_obstacle_height: 0.5
      min_obstacle_height: 0.0
      obstacle_range: 1.0
      raytrace_range: 1.0
      inf_is_valid: true

  inflation_layer:
    inflation_radius: 0.15

  global_frame: odom
  rolling_window: true
  width: 2
  height: 2
